### PR TITLE
Dev issue268 - Wall logic

### PR DESCRIPTION
**Pull request by sdiaz7**
Issue #268 

Features implemented:
- Wall can block enemy path
- Wall can be attacked by enemies
- Wall purchasable through the GUI.

There's plenty of images at issue #268, go there to see some examples of the features implemented.

As said, walls can be purchased through the GUI:
image

I am currently using the 3rd tower's icon to represent the wall. The election is purely arbitrary, as such feature will be adressed at issue #245. 
For testing this issue I recommend placing wall objects to the scene rather than buying them, as without tower rotation (#271) wall placement is still very limited.

### CODE REVIEW

**Review by agonzatr17 — APPROVED** [review]
Walls can be placed using the temporary button and they behave properly. Walls use the same behavior script as towers (TowerBehavior) but they are not able to shoot. You can rotate the wall while placing it and cannot place them over another object (as I said, same as towers). The wall stats is placed in the tower xml file, where you can find the cost and health (its only useful characteristics). If enemies are blocked they start attacking a wall.

There are a lot of examples with photos in the issue #268 , but I am providing a personal trial.
review2_foto1

**Review by agonzatr17 — CHANGES_REQUESTED** [review]
Just saw a bug related with the xml file for the upgrades. When you select a wall it shows a tower stat, in this example the "triumphal tower".

Edit: 
The tower file loaded is the last tower selected, so the stats that appear are from that tower. It must be because the tower selection cannot find the next level stats for the wall (wall only has 1 level while towers have 3) and uses the last tower stats that were loaded. 

**Solution: a simple reset on the stored values just before showing the stats of a selected wall should be enough (so that it will show 0 in each stat). As it is a bug not related with the work done in this issue I recommend to contact with kazusaki1 as he did the drawing tower stats (pull request #269) and knows how it works.** 

Even better (to do in another issue): it would be interesting to show another kind of stats, for example just showing health stat (instead of damage, range and fire rate).

review2_foto2

**Comment by agonzatr17** [comment]
**SOLVED: I proceeded to solve the problem, I will wait for someone to review my commit, it can be yourself sdiaz7**

**Review by agonzatr17 — APPROVED** [review]

**Comment by sdiaz7** [comment]
El fix en el menú de torre va perfecto. Para que el de wall no se vea tan vacío voy a añadir el health de la torre. Cierro la pull request. La reabriré una vez haya acabado de implementar la feature.

**Comment by agonzatr17** [comment]
El PR ha sido finalizado en #278 dado que hacia falta una nueva implementación para dar soporte visual al nuevo botón de "comprar wall".

**Pull request closed without merging**
